2020-12-26 13:23:21,765 ERROR: Exception on /edit_profile [POST] [in c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\routes.py", line 109, in edit_profile
    db.session.commit()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 1046, in commit
    self.transaction.commit()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 504, in commit
    self._prepare_impl()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 483, in _prepare_impl
    self.session.flush()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 2540, in flush
    self._flush(objects)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\session.py", line 2642, in _flush
    flush_context.execute()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\persistence.py", line 230, in save_obj
    _emit_update_statements(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\orm\persistence.py", line 994, in _emit_update_statements
    c = cached_connections[connection].execute(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\sqlalchemy\engine\default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=? WHERE user.id = ?]
[parameters: ('Susan', 3)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
2020-12-26 18:33:44,694 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:69]
2020-12-26 18:35:41,749 ERROR: Exception on /reset_password_request [POST] [in c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\jebakuma\.virtualenvs\microblog_clean-uu0fvpk6\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\routes.py", line 185, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\email.py", line 13, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\models.py", line 109, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2020-12-26 19:20:10,786 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:69]
2020-12-26 19:23:14,859 INFO: Microblog startup [in C:\Users\jebakuma\OneDrive - HP Inc\learning\flask\flask-mega-tutorial-miguel-grinberg\microblog_clean\application\__init__.py:69]
